name: 'unit-end-action'
description: 'Composite action for end of unit tests'
inputs:
#  text:
#    description: "text for slack message"
#    required: false
#    default: "${{ github.repository }} unit test"
#  status:
#    description: "Job Status"
#    required: false
#    default: "${{ job.status }}"
#  author_name:
#    description: "Message author name for slack message"
#    required: false
#    default: "${{ github.repository }} ${{ github.workflow }}"
#  slack_webhook_url:
#    description: ""
#    required: true
#    default: "" # remove this when we can make notify a part of this step
  uploadArtifactName:
    description: "Name of uploaded artifact"
    required: false
    default: upload-artifacts
  artifactPath:
    description: "Path to upload as an artifact"
    required: false
    default: "var"
  githubEventAction:
    description: "github.event.action"
    required: false
    default: "${{ github.event.action }}"
  githubEventName:
    description: "github.event_name"
    required: false
    default: "${{ github.event_name }}"
outputs:
  matrix:
    description: "Deployment matrix"
    value: "${{ steps.set-matrix.outputs.matrix }}"
  stage:
    description: "Feature stage"
    value: "${{ steps.set-feature-stage.outputs.stage }}"
runs:
  using: "composite"
  steps:
    - name: Notify Slack
      id: notify-slack
      uses: 8398a7/action-slack@v3.9.2
      if: always() && github.actor != 'dependabot[bot]'
      with:
        text: ${{ inputs.text }}
        status: ${{ inputs.status }}
        author_name: ${{ inputs.author_name }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.uploadArtifactName }}
        path: ${{ inputs.artifactPath }}
